import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./header";
import { Meteors } from "@/components/ui/meteors";
import Footer from "@/components/footer";
// import { ClerkProvider } from "@clerk/nextjs/dist/types/components.server";
import {
	ClerkProvider,
	SignInButton,
	SignedIn,
	SignedOut,
	UserButton,
} from "@clerk/nextjs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<ClerkProvider>
			<html lang="en">
				<body>
				
					<SignedOut>
						<SignInButton />
					</SignedOut>
					<SignedIn>
						<UserButton />

						<Header />
						<div className="mb-3 mt-3">{children}</div>
						<Footer />
					</SignedIn>
				</body>
			</html>
		</ClerkProvider>
	);
}
